getsentry/sentry-capacitor

android/src/main/java/io/sentry/capacitor/SentryCapacitor.java, src/backend.ts, src/definitions.ts, src/web.ts, src/wrapper.ts, test/backend.test.ts, test/wrapper.test.ts
This implements the captureMessage and captureException functionality in android and in the JS middleware. There are also fixes to the tests and updates to the type of data being sent to captureEnvelope and getStringBytesLength (the wrong data was previously being sent).
Testing of both the captureException and captureMessage methods was used in a project I created on the Sentry website, and both events were successfully sent:
=> fix: updated type of data received to fix captureenvelope and getstringbyteslength android methods

README.md
Updates the readme with the new installation for angular and the init method from #35
=> meta: Updated readme with new installation and init methods

src/index.ts, src/integrations/eventorigin.ts, src/integrations/index.ts, src/integrations/sdkinfo.ts, src/sdk.ts
Adds the `event.origin` and `event.environment` tag as a default integration. Also refactors the sdk info event processor into a default integration.
Tested on sample app with multiple events.
=> feat: Add event origin tag and also move sdkInfo into an integration

android/build.gradle, android/src/main/java/io/sentry/capacitor/SentryCapacitor.java, src/wrapper.ts
Bumps the Sentry Android SDK to 5.0.1.
Additional Changes:
- Updates the `captureEnvelope` method to get the outboxPath from `HubAdapter`. A recent fix in React Native.
- Adds the native SDK's packages to the sdk info on events sent from the JS layer.
- Moves the event origin tag into its own method to align with other sdks.
Tested on the sample app with a multitude of events including native crashes.
=> build(android): Bump sentry-android to 5.0.1

android/src/main/java/io/sentry/capacitor/SentryCapacitor.java, example/ionic-angular-v2/src/app/tab1/tab1.page.html, example/ionic-angular-v2/src/app/tab1/tab1.page.ts, example/ionic-angular-v2/yalc.lock, example/ionic-angular/src/app/tab1/tab1.page.html, example/ionic-angular/src/app/tab1/tab1.page.ts, ios/Plugin/Plugin.m, ios/Plugin/Plugin.swift, src/definitions.ts, src/scope.ts, src/wrapper.ts, test/wrapper.test.ts
Add scope sync methods for `setTag`, `setExtra`, `setUser`, `addBreadcrumb`, `clearBreadcrumb` for iOS. 
Fixes `setUser` not taking non-default data and `clearBreadcrumbs` on Android.
Adds test for the JS side of the bridge, and methods to test scope sync on the sample apps.
Tested on the v3 sample app.
=> feat: Finish scope sync for both iOS and Android

CHANGELOG.md, example/ionic-angular-v2/package.json, example/ionic-angular-v2/yalc.lock, example/ionic-angular-v2/yarn.lock, example/ionic-angular/package.json, example/ionic-angular/yarn.lock, package.json, src/transports/native.ts, yarn.lock
Also fixes version mismatch issues with sibling SDKs.
Fixes #66
=> build(js): Bump sentry-javascript dependencies to 6.11.0

package.json, src/index.ts, src/transports/native.ts, yarn.lock
- No longer export deprecated Status enum
- Remove guard from transport `sendEvent` as it is redundant
=> feat(deps): Bump Sentry SDKs to 6.17.4

CHANGELOG.md, src/wrapper.ts, test/wrapper.test.ts
Because of that, the Length was being set with the size of the string, which resulted in ok behaviors if the serialized string was in UTF-8, but if someone decided to add an UTF-16/32 character, would result on the wrong length of the envelope.
This PR awaits for getStringBytesLength to be conclude and sets the length with the value from the native callback.
Close #124
=> await for getStringBytesLength

CHANGELOG.md, src/wrapper.ts, test/wrapper.test.ts
This parameter is only used on the Javascript side of the SDK and shouldn't be sent to the Native event handler.
Closes #125.
=> remove sdkProcessingMetadata from native events

CONTRIBUTING.md, example/ionic-angular-v2/README.md, example/ionic-angular/README.md
just some quality of life information that will help folks to setup Sentry-Capacitor and the included examples.
=> Add missing setup information

CHANGELOG.md, src/options.ts, src/sdk.ts
Add an option filter to avoid registering out of error events if the user doesn't want it.
Partially solves #127
=> Add Missing config `enableOutOfMemoryTracking` for iOS/Mac

CHANGELOG.md, ios/Plugin/Plugin.m, ios/Plugin/Plugin.swift
Not sure how but, getStringBytesLength was missing from iOS so I just implemented it
Fixes #124 and #100
Tested event: https://sentry.io/organizations/sentry-sdks/discover/sentry-capacitor:b7e9eb1c22f34d1b84f0b085db3a733a/?field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&project=5522756&query=&sort=-timestamp&statsPeriod=1h&yAxis=count%28%29
=> Fix iOS dropping envelopes with UTF16 characters

CHANGELOG.md, example/ionic-angular-v2/package.json, example/ionic-angular-v2/yalc.lock, example/ionic-angular-v2/yarn.lock, example/ionic-angular/package.json, example/ionic-angular/yarn.lock, package.json
This change will also require 
- @sentry/angular": "6.19.2"
- @sentry/react": "6.19.2"
- @sentry/vue": "6.19.2"
=> Bump sentry javascript to 6.19.2

.eslintrc.js, CHANGELOG.md, ios/Plugin/Plugin.m, ios/Plugin/Plugin.swift, src/definitions.ts, src/integrations/devicecontext.ts, src/integrations/index.ts, src/sdk.ts, src/wrapper.ts, test/wrapper.test.ts
With this change the native context will be connected to the JS one.
Close #138 
Before:
After:
=> Add iOS metadata to JavaScript events

yarn.lock
Release.yml doesn't like when it produces uncommitted changes to the local branch.
Ideally in the future this check should be done during the PR and not on the release phase.
=> fix update yarn.lock

CHANGELOG.md, android/src/main/java/io/sentry/capacitor/SentryCapacitor.java
When invoking `Sentry.nativeCrash`, plugin crashes with following logcat output:
```
E/Capacitor: Serious error executing plugin
java.lang.IllegalArgumentException: Wrong number of arguments; expected 0, got 1
at java.lang.reflect.Method.invoke(Native Method)
at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121)
at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:598)
at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(Unknown Source:8)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.os.HandlerThread.run(HandlerThread.java:67)
```
Instead of `java.lang.RuntimeException: TEST - Sentry …
=> Android: Fix java.lang.IllegalArgumentException

ios/Plugin/Plugin.swift
Fixes first issue of https://github.com/getsentry/sentry-capacitor/issues/176.
I have no experience with swift, but since the `payloadSize` is being tested against `nil`, it should be safe for force Int
=> iOS: Avoid warning by force-unwrapping value

CHANGELOG.md, SentryCapacitor.podspec, android/build.gradle, ios/Podfile, package.json
capacitor 4.0.0 deployed! ([release](https://github.com/ionic-team/capacitor/releases))
so fixes `error: compiling for iOS 12.0, but module 'Capacitor' has a minimum deployment target of iOS 13.0`
=> Add support for Capacitor 4.0.0

CONTRIBUTING.md, SentryCapacitor.podspec, ios/Podfile, ios/Podfile.lock, yarn.lock
hey 👋🏻 ! would like to bump sentry-cocoa to latest release as we're getting some false positives for OOM errors and also this warning:
```
We recommend you [update your SDK from sentry.cocoa@v7.11.0 to sentry.cocoa@v7.23.0](https://docs.sentry.io/platforms/cocoa/?_ga=2.14415799.1295930408.1661351982-2002825694.1654264158) (All sentry packages should be updated and their versions should match)
```
NOTE: I've followed the contribution guidelines but not sure about the changes around capacitor 4
=> feat: bump sentry-cocoa to 7.23.0

CHANGELOG.md, CONTRIBUTING.md
0.9.0 was missing the version bump info and the fixes info was in front of the features info.
fix typo on contributing.md
=> NIT contributing.md/changelog

CHANGELOG.md, example/ionic-angular/android/app/build.gradle, example/ionic-angular/android/app/src/main/AndroidManifest.xml, example/ionic-angular/android/build.gradle, example/ionic-angular/android/gradle/wrapper/gradle-wrapper.properties, example/ionic-angular/android/variables.gradle, example/ionic-angular/package.json, example/ionic-angular/yarn.lock, package.json, yarn.lock
Also fixes the Sample that broke on the latest Android Studio.
=> Bump Sentry JavaScript SDK to 7.13.0

CHANGELOG.md, SentryCapacitor.podspec
Yarn PNP uses a different method of managing Packages, eliminating the need for the node_modules folder. By doing that, the current podspec code is not able to find the Capacitor package to check if the user is using Capacitor 3 or 4.
The fix sets a minimum compatible version with Capacitor 4 if the required package was not found, avoiding the app to not sync due to issues on podspec.
Partially fixes #221
=> Fallback to iOS minimum version 13.0 if Capacitor package was not found

CHANGELOG.md, CONTRIBUTING.md, android/build.gradle
This PR Bumps Sentry Android 5.7.0 to 6.4.3 and also updates the contributing page.
=> Bump Android SDK to 6.4.3

CHANGELOG.md, src/wrapper.ts, test/wrapper.test.ts
Unhandled Exceptions doesn't crash the app, unlike React Native, so we shouldn't validate the Handled flag for clearing the breadcrumbs.
For context: Both SDKs have the same Breadcrumbs, we clear them on the Android Wrapper because the Android SDK will apply the same breadcrumbs to the captured event.
Fixes #232
=> Avoid duplicating Breadcrumbs on Android

.eslintignore, CHANGELOG.md, README.md, package.json, scripts/check-siblings.js
The goal is to better inform the user that Sentry/Capacitor requires the exact version on the Sibling SDKs as defined on the peerDependency.
This code will look for any @sentry/package references on the packages.json file from the user's project, if those references doesn't match the required one by the script, the script will warn the user about it when a dependency gets installed or updated.
Some questions in regard to this feature:
- Should it feature just warn the user or throw an error when installing/updating the dependency?
If we throw an error, the user will only be able to update the project if he/she updates all sibling dependencies in one command (ie yarn add @sentry/angular@7.15.0 @sentry/hub@7.15.0 @sentry/capacitor@0.11.0 --exact)
Fixes #45, #218, #268
=> Add sibling check

.eslintrc.js, CHANGELOG.md, example/ionic-angular/package.json, example/ionic-angular/yarn.lock, package.json, scripts/check-siblings.js, src/definitions.ts, src/integrations/devicecontext.ts, src/integrations/eventorigin.ts, src/integrations/sdkinfo.ts, src/options.ts, src/plugin.ts, src/scope.ts, src/sdk.ts, src/transports/native.ts, src/wrapper.ts, test/sdk.test.ts, test/transports/native.test.ts, test/wrapper.test.ts, yarn.lock
This PR Bumps the Javascript SDK Dependencies and also fixes the changes required in order to be compatible with it.
=> Bump Javascript SDK 7.31.1

CHANGELOG.md, scripts/check-siblings.js
This PR fixes an incorrect reference  to the package.json.
The path.join() method concatenates all given path segments into a single path, handling the appropriate platform-specific separators and making it less prone to errors.
Fixes #298
=> fix incorrect reference to package.json under special cases

CHANGELOG.md, example/ionic-angular/package.json, example/ionic-angular/yarn.lock, package.json, yarn.lock
This PR Bumps Sentry Javascript from version to 7.31.1 to 7.37.1
=> Bump Sentry Javascript 7.37.1

CHANGELOG.md, scripts/check-siblings.js
Sentry Electron uses a different versioning number so it should be ignored from the sibling check, otherwise users will have to ignore the sibling check order to use the SDK.
=> Ignore Sentry Electron from Sibling Checks

CHANGELOG.md, android/src/main/java/io/sentry/capacitor/SentryCapacitor.java, example/ionic-angular/android/gradle.properties, example/ionic-angular/ios/App/App.xcodeproj/project.pbxproj, example/ionic-angular/ios/App/Podfile, example/ionic-angular/package.json, example/ionic-angular/src/app/app.module.ts, example/ionic-angular/yarn.lock, package.json, src/sdk.ts, src/transports/TextEncoder.ts, src/transports/native.ts, src/wrapper.ts, test/vendor/buffer/utf8ToBytes.test.ts, test/vendor/buffer/utf8ToBytesSize.test.ts, test/wrapper.test.ts, yarn.lock
This PR Bumps Sentry JavaScript and their siblings to 7.50
This PR also contains minor fixes:
- Fixed minimum version of iOS on the sample in order to be compatible with the latest Capacitor (no impact on the SDK itself)
- Changed the Transport in order to be more compatible with the latest changes of Sentry Replay (required changes in order to be compatible with the latest Replay versions)
- Added missing return on the CaptureEnvelope for the Android SDK (no impact for the current SDK but it's a required change for the new Transport).
- Changed the naming of `makeCapacitorTransport` to `makeNativeTransport`
- Added additional tests to the changes and also to current code that were lacking tests.
Fixes #357
=> Bump Sentry JavaScript 7.50

CHANGELOG.md, src/nativeOptions.ts, src/wrapper.ts, test/nativeOptions.test.ts, test/wrapper.test.ts
Reworked the Capacitor Options sent to native in order to only allow parameters that are supported, the previous filter was weak since new types and custom ones added by the users could have the risk of breaking the native initialisation on iOS.
Fixes #338, may also fix #337
=> Fix iOS not Sending events.

CHANGELOG.md, ios/Plugin/Plugin.swift
This data was moved to the private Private SDK
Fixes #351
=> Fix Deprecated references to Sdk Info

.github/workflows/stale.yml
After reviewing some Issues I noticed that some old issues didn't have any stale warning.
So I just added the missing Github integration that Sentry uses on other Projects.
In this case, it's basically the same implementation as the one done on React Native: https://github.com/getsentry/sentry-react-native/blob/main/.github/workflows/stale.yml
=> add stale.yml

CHANGELOG.md
While trying to resolve the incident around our release registry being out of sync we noticed that the last release of `@sentry/capacitor@0.11.5` was made after `@sentry/capacitor@0.12.1` was already released. This "incorrectly" redirected NPM's `latest` pointer to `0.11.5` instead of `0.12.1`. The simplest way to fix this is to release a new 0.12.x version so this PR updates the changelog for it.
(Note: Alternatively, merging any open PR that updates the changelog would also do. Happy to close this if we can make a somewhat meaningful release)
=> chore: Update CHANGELOG for 0.12.2

src/scope.ts, src/utils/normalize.ts, src/wrapper.ts, test/utils/normalize.test.ts, test/wrapper.test.ts
When trying to serialize an object like this
```typescript
const subObject: { sub1: string, sub2: any } = { sub1: 'subObjectValue', sub2: undefined }
const givenObject = { root1: 'some value', root2: subObject };
subObject.sub2 = givenObject;
```
one will get an error like this
```
TypeError: Converting circular structure to JSON
--> starting at object with constructor 'Object'
|     property 'b' -> object with constructor 'Object'
--- property 'd' closes the circle
at JSON.stringify (<anonymous>)
```
This PR fixes this behavior. A "flattened" output can be seen in the added [unit test](https://github.com/mlostekk/sentry-capacitor/blob/0eb8660011376c315d80a33c6a2b1b77750e69f0/test/wrapper.test.ts#L632).
=> Fix error when serializing objects with circular referencing

CHANGELOG.md, example/ionic-angular-v5/ios/App/Podfile.lock, ios/Plugin/Plugin.swift
We must guarantee that Sentry Cocoa initialises on the Main Thread, usually this is the expected flow that usually happens but there are cases where It'll be initialised on another thread and may lead to a Crash.
This fix guarantees that Sentry Cocoa is always initialised on the main thread
Fixes: #424, #443, #207
Lastly, added the missing pod file for one of the samples, it has no impact on the main code and it's always generated when building.
=> Fix: Always start Sentry Cocoa on Main Thread

CHANGELOG.md, src/nativeOptions.ts, src/options.ts, src/sdk.ts, test/nativeOptions.test.ts
New implementation of Sentry Cocoa uses `enableWatchdogTerminationTracking` instead of  `enableOutOfMemoryTracking `
This PR fixes the correct value to be sent to the Native SDK, allowing both methods to be used, and also deprecates enableOutOfMemoryTracking to warn users that this feature will be removed on a major version.
Fixes #445
=> Fix: enableWatchdogTerminationTracking (replaces enableOutOfMemoryTracking) is now properly set on iOS.

CHANGELOG.md, android/build.gradle
This bump include fixes to Hybrid SDKs that fixes the required (now optional) op field from Tracing events and also empty breadcrumb lists.
Fixes #459 and #450
=> Bump Sentry Java 6.31.0

CHANGELOG.md, example/ionic-angular-v2/package.json, example/ionic-angular-v2/yarn.lock, example/ionic-angular-v5/package.json, example/ionic-angular-v5/yarn.lock, example/ionic-angular/package.json, example/ionic-angular/yarn.lock, package.json, yarn.lock
Additionally, the replay package was removed from the samples since it is already bundled with the main SDK.
=> Bump Sentry JavaScript 7.73.0

package.json, src/index.ts, src/sdk.ts, tsconfig.build.json, tsconfig.esm.json, yarn.lock
A fresh npm install has peer dependency issues because of a conflict in the typescript version and the `@sentry/typescript` version.
I saw that it was renamed long ago to `sentry-internal/typescript`, so I've updated the plugin to use that instead and also fix the issues generated from the package change.
=> chore: Use sentry-internal/typescript instead of sentry/typescript

src/sdk.ts, src/utils/webViewUrl.ts
Instead of hardcoding the replacement of the Capacitor url for just `https://localhost` and `capacitor://localhost`, use the value on `window.WEBVIEW_SERVER_URL` that Capacitor sets with the proper value based on the user scheme and hostname configuration.
I had to disable some eslint rules for the line, let me know if there is a better approach
closes https://github.com/getsentry/sentry-capacitor/issues/440
closes https://github.com/getsentry/sentry-capacitor/issues/391
=> fix: correct the capacitor url replacement

CHANGELOG.md, example/ionic-angular-v2/.gitignore, example/ionic-angular-v2/package.json, example/ionic-angular-v2/src/app/app.module.ts, example/ionic-angular-v2/yarn.lock, example/ionic-angular-v5/.gitignore, example/ionic-angular-v5/package.json, example/ionic-angular-v5/src/app/app.module.ts, example/ionic-angular-v5/yarn.lock, example/ionic-angular/.gitignore, example/ionic-angular/angular.json, example/ionic-angular/package.json, example/ionic-angular/src/app/app.module.ts, example/ionic-angular/yarn.lock, src/index.ts
Exposes Replay and BrowserTracing that were already bundled by @sentry/browser to @sentry/capacitor so users can refer to a single SDK for those references, instead of importing a sibling SDK or sentry/browser for that
Before:
```javascript
import * as Sentry from '@sentry/capacitor';
import * as SentryBrowser from '@sentry/browser';
Sentry.init(
integrations: [
new SentryBrowser.BrowserTracing({routingInstrumentation}),
new SentryBrowser.Replay({
maskAllText: false,
blockAllMedia: true,
}),
],
```
After:
```javascript
import * as Sentry from '@sentry/capacitor';
Sentry.init(
integrations: [
new Sentry.BrowserTracing({routingInstrumentation}),
new Sentry.Replay({
maskAllText: false,
blockAllMedia: true,
}),
],
```
Minor changes:
-Update Samples with Sentry/Angular-ivy (recommended SDK for …
=> Feat: Expose Replay and BrowserTracing

CHANGELOG.md, example/ionic-angular-v2/package.json, example/ionic-angular-v2/yarn.lock, example/ionic-angular-v5/package.json, example/ionic-angular-v5/yarn.lock, example/ionic-angular/package.json, example/ionic-angular/yarn.lock, package.json, yarn.lock
Bumps the sibling SDKs to 7.81.1
=> Bump: Sentry Javascript 7.81.1

CHANGELOG.md
SDK will be updated back on the next release.
=> Rollback changelog for sibling SDK

src/client.ts, src/integrations/sdkinfo.ts, test/client.test.ts
This PR Implements the missing layer to capture user feedbacks from the Capacitor Client.
Sub-Task of #573
=> Fix: Implement userfeedback layer for Capacitor Client Layer

CHANGELOG.md, src/wrapper.ts, test/wrapper.test.ts
When no DSN is provided, the `initNativeSdk` function returns before the `enableNative` option is set. Effectively rendering the option useless.
This causes, the native sdk to still perform the checks of whether the native client is available and if that is not the case, then throws the `NativeClientError`.
A simple reproduction example would be:
```typescript
Sentry.init({
dsn: undefined,
enableNative: false,
});
setUser(null);
```
the `setUser` call will throw the NativeClientError.
I chose to set `enableNative` to false regardless of the provided option since the warning message that gets logged when the DSN is not provided states "... Native SDK will also not be initialized.", which should be enough of a hint that the native sdk will not function regardless of the provided …
=> fix: disable native sdk if DSN is not provided

CHANGELOG.md, src/nativeOptions.ts, src/options.ts, test/nativeOptions.test.ts
This feature allow users to disable or increase the time of the app hang events.
Without it, Sentry will create events similar to the following one when the app hangs the UI:
https://sentry-sdks.sentry.io/issues/5080073190/events/018e7e8767624078b7fe1422b415231d
by disabling enableAppHang, Sentry will no longer create the hang events.
Close #596
=> Feat: Add enableAppHangTracking and appHangTimeoutInterval.

CHANGELOG.md, SentryCapacitor.podspec, example/ionic-angular-v2/package.json, example/ionic-angular-v5/ios/App/Podfile.lock, example/ionic-angular-v5/package.json, example/ionic-angular/package.json, example/ionic-vue3/ios/App/Podfile.lock, example/ionic-vue3/package.json, ios/Podfile, ios/Podfile.lock, package.json
Version 8.22.2/8.22.1/8.22.0 aren't working with HybridSDKs at the moment and a fix is expected soon, in the meantime we'll bump the SDK to a lower version, not being a downgrade to the users since the latest released version had a lower version for Sentry Cocoa.
This PR also adds an extra script for updating the pod files from the Samples.
=> Bump: Downgrade Sentry cocoa to 8.21.0

android/src/main/java/io/sentry/capacitor/SentryCapacitor.java, example/ionic-angular-v5/ios/App/Podfile.lock, ios/Plugin/Plugin.swift
This PR fixes some deprecated warnings from both Sentry Native and Capacitor dependency.
No break changes were introduced with this PR.
=> Fix: Deprecated warnings

.github/workflows/buildandtest.yml, example/ionic-angular-v3/package.json, package.json, yarn.lock
Previously the tests of bumping the samples and testing the build was run sequentially, due to the amount of samples we are using the CI for building PRs was getting slower.
The PR implements two changes: 
- Github Actions: a vm for each test, and reuse of the built capacitor package.
- Local: use the concurrency dependency allowing to build and test all samples in parallel.
I tried using the concurrency and similar methods to only use a single VM on Github Actions but yarn seems too unstable when installing from multiple sources at the same time so I opted for using the simpler version of just using multiple macos virtual machines.
Measured time: before : 8 minutes, after: 1 minute 30 seconds
- Minor change: 
- moved the build job to the top since the below jobs depends on it (just a …
=> Ref: Run sample update concurrently

CHANGELOG.md, android/src/main/java/io/sentry/capacitor/SentryCapacitor.java, example/ionic-angular-v5/ios/App/Podfile.lock, example/ionic-angular-v6/ios/App/Podfile.lock, example/ionic-vue3/ios/App/Podfile.lock, ios/Plugin/Plugin.swift
the behaviour on JavaScript with undefined value is to remove the tag, this wasn't respected on the native SDKs, this PR ensures that the behaviour form JavaScript also happens on the Native layer, by removing the tag.
Fixes: #647
=> Fix: Accept undefined as value for tags.

CHANGELOG.md, src/index.ts
The following exports are now exposed from Sentry core:
-   flush,
-   getActiveSpan,
-   spanToJSON,
-   spanIsSampled,
-   setMeasurement,
-   getGlobalScope,
-   getIsolationScope,
-   getClient,
-   setCurrentClient,
-   metrics,
They were tested locally and there will be a follow up PR for using those exports on the sample app (https://github.com/getsentry/sentry-capacitor/issues/665)
=> Expose missing exports from sentry core

CHANGELOG.md, android/src/main/java/io/sentry/capacitor/SentryCapacitor.java, example/ionic-angular-v3/src/app/tab2/tab2.page.html, example/ionic-angular-v3/src/app/tab2/tab2.page.ts, example/ionic-angular-v4/src/app/tab2/tab2.page.html, example/ionic-angular-v4/src/app/tab2/tab2.page.ts, example/ionic-angular-v5/src/app/tab2/tab2.page.html, example/ionic-angular-v5/src/app/tab2/tab2.page.ts, example/ionic-angular-v6/android/app/src/main/assets/capacitor.config.json, example/ionic-angular-v6/capacitor.config.ts, example/ionic-angular-v6/ios/App/App/capacitor.config.json, example/ionic-angular-v6/src/app/tab2/tab2.page.html, example/ionic-angular-v6/src/app/tab2/tab2.page.ts, ios/Plugin/Plugin.m, ios/Plugin/Plugin.swift, package.json, src/definitions.ts, src/index.ts, src/sdk.ts, src/wrapper.ts, test/wrapper.test.ts
This PR exposes the close function that closes the client and the native layer.
Minor changes:
* Removed deprecated flags from the latest samples.
* Added a button to call the close function.
Closes #663
=> Feat: Add close function to the main SDK.

scripts/update-javascript.sh
They no longer exist on v8 so I am removing them from the script check.
Close #511 
=> Remove hub and tracing from  update-javascript.sh

CHANGELOG.md, example/ionic-angular-v3/package.json, example/ionic-angular-v3/yarn.lock, example/ionic-angular-v4/package.json, example/ionic-angular-v4/yarn.lock, example/ionic-angular-v5/package.json, example/ionic-angular-v5/yarn.lock, example/ionic-angular-v6/package.json, example/ionic-angular-v6/yarn.lock, example/ionic-vue3/yarn.lock, package.json, yarn.lock
This PR will bump Sentry JavaScript to 8.27.0. No break changes were noted with the previous version
=> bump Sentry JavaScript to 8.27.0

ios/Podfile.lock
Fix pod lock with the wrong version, should only impact CI builds.
=> fix: wrong pod lock files version

.github/workflows/buildandtest.yml, CHANGELOG.md, src/utils/normalize.ts, test/utils/normalize.test.ts
This change allows Breadcrumbs to respect the defined limits of `normalizeDepth` and `normalizeMaxBreadth`.
Before that, it would use the limits of 100 for `normalizeDepth` and infinite for `normalizeMaxBreadth`
The PR also updates GitHub Checks that were using old versions, which were blocking the build to pass.
=> Fix: normalize should use Options limits or default

scripts/check-siblings.js
I'm using `@sentry/nextjs` version `8.27.0`, and I cannot update to the latest version because of a [bug](https://github.com/getsentry/sentry-javascript/issues/14077) introduced in the next version. And there was another [bug](https://github.com/getsentry/sentry-javascript/issues/13270) on `8.27.0`. So I had to use `yarn patch` to fix the latter mentioned bug without updating the package.
`yarn patch` changes the version to something like this: `patch:@sentry/nextjs@npm%3A8.27.0#~/.yarn/patches/@sentry-nextjs-npm-8.27.0-0e3a1ce4c2.patch` This means that exact version `8.27.0` was used as base and patched.
This PR updates the sibling version check to work with `yarn patch` versions.
=> scripts/check-siblings: Update to work with yarn patch.

CHANGELOG.md, tsconfig.build.json
=> fix: use commonjs modules in commonjs build

CHANGELOG.md, src/index.ts
This PR adds missing span utils export from @sentry/core.
=>  fix(core): Export missing span utils from Sentry Core 

package.json
Ionic usually gets the wrong of the SDK, despite the right one being installed, adding the --sig parameter to publish will add the hash of the SDK and will avoid conflicts with wrong versions being tested with the sample.
More information: https://github.com/wclr/yalc?tab=readme-ov-file#publish
=> Ref: use --sig parameter when bumping samples

.github/workflows/buildandtest.yml, .github/workflows/release.yml, CONTRIBUTING.md, package.json
Since other SDKs are using corepack and the change was simple here, I thought on enabling it here so it avoids corepack trying to install the incorrect version of yarn every time I work on Capacitor with corepack enabled.
=> internal: Enable corepack

CHANGELOG.md, example/ionic-angular-v3/package.json, example/ionic-angular-v3/yarn.lock, example/ionic-angular-v4/yarn.lock, example/ionic-angular-v5/yarn.lock, example/ionic-angular-v6/yarn.lock, example/ionic-vue3/package.json, example/ionic-vue3/yarn.lock, package.json, yarn.lock
This PR bumps Sentry/Javascript to version 8.37.1.
No break changes were encountered.
=> Bump Sentry/Javascript 8.37.1

test/utils/normalize.test.ts
PR Aimed to fix the normalized tests that started to fail on the latest JavaScript SDK.
=> Fix: normalize test

src/nativeOptions.ts
This update addresses an issue where the tracePropagationTargets option was being ignored in various CapacitorHTTP methods.
=> Bugfix: tracePropationTargets option ignored in CapacitorHTTP methods

src/nativeOptions.ts
Reverts getsentry/sentry-capacitor#803
We will keep track of the feature here: https://github.com/getsentry/sentry-capacitor/issues/820
=> Revert "Bugfix: tracePropationTargets option ignored in CapacitorHTTP methods"

.github/workflows/buildandtest.yml
Github is failing the builds using this package on older version so I bumped the version of it.
Error Log:
https://github.com/getsentry/sentry-capacitor/actions/runs/13268970657/job/37043558127
=> Update Actions/Cache to  v4.2.0

scripts/update-javascript.sh
Sentry JavaScript V9 no longer uses sentry/utils and it is now deprecated, this PR removes this package from the update list.
=> ref: remove sentry utils update

CHANGELOG.md
Previous [PR](https://github.com/getsentry/sentry-capacitor/pull/855) was contributed by an external contributor, this PR only updates the changelog with information regard to his PR.
=> Ref: Update changelog

example/ionic-angular-v5/ios/App/Podfile.lock, example/ionic-angular-v6/ios/App/Podfile.lock, example/ionic-angular-v7/ios/App/Podfile.lock, example/ionic-vue3/ios/App/Podfile.lock
#skip-changelog 
Fixes https://github.com/getsentry/sentry-capacitor/pull/751, which have not updated the lock file automatically
=> chore: update Sentry version to 8.48.0 in Podfile.lock files

CHANGELOG.md, example/ionic-angular-v3/package.json, example/ionic-angular-v3/yarn.lock, example/ionic-angular-v4/package.json, example/ionic-angular-v4/yarn.lock, example/ionic-angular-v5/package.json, example/ionic-angular-v5/yarn.lock, example/ionic-angular-v6/package.json, example/ionic-angular-v6/yarn.lock, example/ionic-angular-v7/package.json, example/ionic-angular-v7/yarn.lock, example/ionic-vue3/package.json, example/ionic-vue3/yarn.lock, package.json, test/sdk.test.ts, yarn.lock
This is a small bump prior V9 to fix vulnerabilities.
=> Bump Sentry Javascript to 8.55.0

example/ionic-angular-v6/ios/App/Podfile.lock, example/ionic-angular-v7/ios/App/Podfile.lock, example/ionic-vue3/ios/App/Podfile.lock, ios/Plugin.xcodeproj/project.pbxproj, ios/Podfile, ios/Podfile.lock
The main podfile was updated by the bot but it forgot to update the samples and also the lockfiles.
This PR updates the podfiles, along to pointing to a newer capacitor podfile that is not deprecated.
=> Ref: podfile update

CHANGELOG.md, android/build.gradle, package.json, yarn.lock
To keep development of the SDK not too complex, we will drop Capacitor versions that are no longer maintained by Capacitor itself.
Fixes https://github.com/getsentry/sentry-capacitor/issues/893
pod issues will be fixed here https://github.com/getsentry/sentry-capacitor/pull/909
=> Ref: Clear old capacitor version support

CHANGELOG.md, src/options.ts
On strict builds, the original reference of `BrowserTransportOptions` is not accepted.
By using `Parameters<typeof makeFetchTransport>[0]` we are able to get the original type of `BrowserTransportOptions` while keeping it compatible with strict builds of Typescript.
Same fix already exists on React Native: https://github.com/getsentry/sentry-react-native/blob/ffab99479d130e00dec3443403629a9a99f29a64/packages/core/src/js/options.ts#L11
Fixes: https://github.com/getsentry/sentry-capacitor/issues/933
=> Fix: Can't find BrowserTransportOptions type

src/integrations/sdkinfo.ts, test/extensions/sentryCapacitorJest.ts, test/integrations/sdkinfo.test.ts, test/mocks/capacitor.ts, test/nativeOptions.test.ts, test/wrapper.test.ts
There was an intermittent flakiness that was more visible on Github CI than local, all started with 1276dfbe7c618b0e6b6fe7661f7f88dd19add64c, the additional tests probably made it more flaky than usual.
The mock of Capacitor was standardized in a single file to avoid contamination across test files, the usage of doMock also helped to make sure the timings of tests works correctly.
=> Fix native options test

example/ionic-angular-v6/ios/App/App/capacitor.config.json, example/ionic-angular-v7/ios/App/App/capacitor.config.json, example/ionic-angular-v7/ios/App/CapApp-SPM/Package.swift
Since Sentry Capacitor supports SPM, we no longer need to rely on auto generated SPM packages.
This PR clears up the previously auto generated files to use the correct SPM package for Sentry Capacitor.
=> Ref: Refer to SPM Sentry Capacitor on Sample apps

CHANGELOG.md, example/ionic-angular-v6/ios/App/Podfile.lock, example/ionic-angular-v7/ios/App/Podfile.lock, example/ionic-vue3/ios/App/Podfile.lock, ios/Sources/SentryCapacitorPlugin/SentryCapacitorPlugin.swift
Sentry options initialization has changed on newer versions of Sentry Cocoa, this PR fixes it by using an alternative method of initializing Sentry Options.
Fixes: https://github.com/getsentry/sentry-capacitor/issues/979
=> Fix: internal options init was changed
