- android/src/main/java/io/sentry/capacitor/SentryCapacitor.java
- src/definitions.ts
- src/transports/native.ts
- src/wrapper.ts
Adds captureEnvelope functionality in the main .java plugin file.
> Capture envelope

- android/src/main/java/io/sentry/capacitor/SentryCapacitor.java
- src/definitions.ts
- src/web.ts
- test/backend.test.ts
- test/wrapper.test.ts
Tests broke when I changed how I checked whether the plugin was available, so this fixes what was broken.
> fix: resolve test issues from changing how native availability is checked

- CONTRIBUTING.md
- android/src/main/java/io/sentry/capacitor/SentryCapacitor.java
- test/wrapper.test.ts
Adapts the setUser functionality from the React-Native project.
> feat: add setUser functionality

- CONTRIBUTING.md
- android/src/main/java/io/sentry/capacitor/SentryCapacitor.java
- src/index.ts
- test/backend.test.ts
- test/wrapper.test.ts
Turns out native crash functionality was mostly complete, so I just finished up that last bits like adding in a test and ensuring the native crash method communicates with the SDK
> feat: finish up last bits of native crash functionality

- android/build.gradle
- android/src/main/java/io/sentry/capacitor/SentryCapacitor.java
- example/ionic-angular/android/build.gradle
- example/ionic-angular/android/gradle/wrapper/gradle-wrapper.properties
- example/ionic-angular/src/app/tab2/tab2.page.ts
- example/ionic-angular/src/app/tab3/tab3.page.html
I was originally pulling the wrong type from the PluginCall for the setTag and breadcrumbs methods. I updated the typecasting to the appropriate types and made some small updates to the verbiage in the example app to make the messages clearer.
> add try catch for logger, small updates to example app

- README.md
Add usage and installation instructions to the README for the android alpha release.
> update readme for android alpha release

- android/build.gradle
- example/ionic-angular/android/build.gradle
> build(android): Bump sentry-android to 4.3.0

- SentryCapacitor.podspec
- ios/Podfile
> Update Podfile to target iOS 12

- CHANGELOG.md
- src/index.ts
> fix: Export startTransaction

- src/sdk.ts
`app:///` is only required for custom protocols, where any valid host, eg. `http(s)://example.com` is matched by a default cli `~/` prefix, which acts as a host wildcard.
Keeping `http(s)` hosts intact, also allows us to fetch sources from the internet if that's configured (not even sure if that's doable in capacitor, but I assume yes?).
> fix: Update logic for RewriteFrames

- .eslintignore
- .github/workflows/danger.yml
- CHANGELOG.md
- dangerfile.js
> feat: Add danger and update changelog

- CHANGELOG.md
- src/sdk.ts
- test/sdk.test.ts
> disable native sdk when enablenative is false

- test/sdk.test.ts
After later changes the Stacktrace is working 
> Extra tests for validating Stack Traces

- CHANGELOG.md
- example/ionic-angular/package.json
- example/ionic-angular/yarn.lock
- package.json
- yarn.lock
- Version bump in order to be compatible with the latest version.
- Sample dependency update.
> Bump Sentry Javascript to fix incompatibility with Sentry Tracing

- CHANGELOG.md
- CONTRIBUTING.md
- SentryCapacitor.podspec
- ios/Podfile
- ios/Podfile.lock
- yarn.lock
This is PR https://github.com/getsentry/sentry-capacitor/pull/208 with the Changelog updated.
> Bump Sentry Cocoa

- CHANGELOG.md
- example/ionic-angular/package.json
- example/ionic-angular/yarn.lock
- package.json
- yarn.lock
Bumps to version 7.12.1
Fixes #209
> Bump Javascript version

- .github/dependabot.yml
> Add dependabot filter

- CHANGELOG.md
- example/ionic-angular/package.json
- example/ionic-angular/yarn.lock
- package.json
- src/scope.ts
- src/sdk.ts
- yarn.lock
Bumps version to 7.15.0 and fixes the new deprecated references.
Close #233
> Bump version 7.15.0

- CHANGELOG.md
- example/ionic-angular/package.json
- example/ionic-angular/yarn.lock
- package.json
- yarn.lock
> Bump Sentry Siblings to 7.24.2

- .gitignore
- CHANGELOG.md
- package.json
> Replace prepublishonly by prepack.

- CHANGELOG.md
- android/build.gradle
- android/gradle.properties
- android/gradle/wrapper/gradle-wrapper.properties
- android/src/main/AndroidManifest.xml
https://capacitorjs.com/docs/next/updating/plugins/5-0
Solves #355
> Upgrade to Capacitor 5

- CHANGELOG.md
- example/ionic-angular-v5/package.json
- example/ionic-angular-v5/yarn.lock
- example/ionic-angular/package.json
- example/ionic-angular/yarn.lock
- package.json
- yarn.lock
> Bump Sentry Javascript 7.54.0

- .eslintrc.js
- CHANGELOG.md
- example/ionic-angular-v2/package.json
- example/ionic-angular-v2/yarn.lock
- example/ionic-angular-v5/package.json
- example/ionic-angular-v5/yarn.lock
- example/ionic-angular/package.json
- example/ionic-angular/yarn.lock
- package.json
- src/wrapper.ts
- yarn.lock
- Bump beta version of sentry JavaScript.
- Fix additional eslint changes
> Bump beta version of sentry javascript

- .github/workflows/buildandtest.yml
Committed via https://github.com/asottile/all-repos
> all-repos: update actions/upload-artifact to v4

- scripts/update-javascript-siblings.sh
- scripts/update-javascript.sh
This PR removes version check for dependencies that no longer exists on V8
> fix:remove old dependencies

- CHANGELOG.md
PR only for updating the changelog for the new version 1.0
Close #736
> Release 1.0

- example/ionic-angular-v6/ios/App/App/capacitor.config.json
Removes duplicated `SentryCapacitor` entry
> chore(examples): remove duplicated package entry

- package.json
- yarn.lock
This should fix the security issue 537 
No code impact to end users 
> Bump Sentry Wizard

- CHANGELOG.md
- package.json
- src/version.ts
> Sync release: 2.0.0-beta.1 to main

- example/ionic-angular-v6/package.json
- example/ionic-angular-v6/yarn.lock
- example/ionic-angular-v7/package.json
- example/ionic-angular-v7/yarn.lock
This PR will fix Code Injection from [MOBILE-996](https://linear.app/getsentry/issue/MOBILE-996/code-injection-in-getsentrysentry-capacitor) There is no impact on the main SDK, but this fix fixes the issue on the Sample apps.
> Fix: Bump ionic/cli for v7 sample

- scripts/update-cocoa.sh
With recent changes, we now have to update the podfile along with the swift package, this Package fix the updater to update both packages.
> Add swift package to cocoa updater

- .github/workflows/add-platform-label.yml
Based on https://github.com/getsentry/sentry-react-native/pull/5043
Update add-platform-label workflow label
>  chore(gh): Update add-platform-label workflow label
